### ISSUE TITLE
How do you test for action recognition?

### ISSUE THREAD

**Issue by sukun1045** [xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning#1]
What is the strategy during test step? Are you doing the forward propagation for all test sequences to extract the test features? Then how exactly to do the classification for action recognition problem? Thank you.

**Comment by xrenaa** [comment]
During the test step, in my understanding, we plot the training result and extract and plot the test feature and say the result. 
In the paper, it takes:

> We follow the same evaluation protocol as defined in [36,
> 45]. All models are evaluated for the clustering quality and false positive rate (FPR) on
> the same test set which consists of unseen motion categories. We compute the FPR for
> 90%, 80% and 70% true positive rates. In addition, we also use the Normalized Mutual
> Information measure (NMI) and F1score to measure the cluster quality where the NMI
> is the ratio between mutual information and sum of class and cluster labels entropies
> while the F1score is the harmonic mean of precision and recall.

[36]. Song, H.O., Xiang, Y., Jegelka, S., Savarese, S.: Deep metric learning via lifted structured
feature embedding. In: Computer Vision and Pattern Recognition (CVPR), 2016 IEEE Conference
on. pp. 4004–4012. IEEE (2016)

**Comment by sukun1045** [comment]
What do you mean by plotting the training results? In Song's paper, they use affinity propagation clustering on test set features.

**Comment by xrenaa** [comment]
Just like the picture is shown in README.me. And actually we don't test this re-implement version in a numerical way for we re-implement this paper for another task.

**Comment by sukun1045** [comment]
Oh I see. So the xaxis is the classes, what is the y axis?

**Comment by xrenaa** [comment]
y is the score from the Attentive LSTM network, for the author uses the L2 norm at the end so the score is just a single value.
