### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by rainbow979** [xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning#3]
Since the data is too large, can you provide a pretrained model for testing? Thanks

**Comment by xrenaa** [comment]
Please check if this one is ok: 
[pretrain.pth.zip](https://github.com/xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning/files/4421518/pretrain.pth.zip)
I do not remember exactly, cause it has been a long time.
