### ISSUE TITLE
the data

### ISSUE THREAD

**Issue by liuzheng502** [xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning#7]
The data you provided on drive is lost.
Could you share it again?or give more information about the data format.
you said the key of the json file is "0","1",.....,"15",Each key contains:( _ , 50, 2, 17) pose.what is the 50 mean?  And in the another issue,you said the 2 channels are the x and y coordinates, is that mean the value of the 2 channels are like
[743.7080688476562, 223.71688842773438]  and the 17 mean the keypoint  like "left_elbow"
or 2 channels are just the character x and y, and the 17 is the 17 coordinates in x?

i learn the Deep Learning just a little time, and im in great request of your help
Thank you in advance

**Comment by xrenaa** [comment]
Hi, the data link is updated.

**Comment by liuzheng502** [comment]
thanks,but the link in readme is not update ,and please give your QR code




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 下午4:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning] the data (#7)





 
Hi, the data link is updated.

**Comment by xrenaa** [comment]
https://drive.google.com/file/d/1-H0ywex6KhA68MPiU7i5Apde_MzXg_vK/view?usp=sharing
You do not need pay for this. Hope this data can help you!

**Comment by liuzheng502** [comment]
thank you very much,you are a&nbsp;warrn-hearted person


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月20日(星期四) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xrenaa/Human-Motion-Analysis-with-Deep-Metric-Learning] the data (#7)





 
https://drive.google.com/file/d/1-H0ywex6KhA68MPiU7i5Apde_MzXg_vK/view?usp=sharing
 You do not need pay for this. Hope this data can help you!

**Comment by ZiyuGuo99** [comment]
@xrenaa Thanks for your excellent code. Could you refresh the shared data? The provided new link is lost again.
Thanks!

**Comment by 3DGaussian** [comment]
> The data you provided on drive is lost. Could you share it again?or give more information about the data format. you said the key of the json file is "0","1",.....,"15",Each key contains:( _ , 50, 2, 17) pose.what is the 50 mean? And in the another issue,you said the 2 channels are the x and y coordinates, is that mean the value of the 2 channels are like [743.7080688476562, 223.71688842773438] and the 17 mean the keypoint like "left_elbow" or 2 channels are just the character x and y, and the 17 is the 17 coordinates in x?
> 
> i learn the Deep Learning just a little time, and im in great request of your help Thank you in advance

hi can u share the datase?
